FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get install -y --no-install-recommends curl libgtk-3-dev
# graphics
RUN apt-get install -y --no-install-recommends adwaita-icon-theme-full libcanberra-gtk-module plplot-driver-wxwidgets
RUN apt-get install gnudatalanguage -y
