channels:
  - conda-forge
dependencies:
  - conda-forge::numba
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::cuda-version=12.4
  - conda-forge::matplotlib
  - conda-forge::scipy
  - nvidia/label/cuda-12.4.0::cuda-toolkit
  - ca-certificates
  - certifi
  - openssl
